services:
  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules        # Hindari konflik node_modules host vs container
    command: npm run dev -- -p 3001 -H 0.0.0.0
